### ISSUE TITLE
close unhealthy work

### ISSUE THREAD

**Issue by carl-leopard** [henrylee2cn/goutil#4]
你好， 最近看了一下你的视频和源码。
在 hire worker的时候进行了worker的健康状态检查。
假设有这样一个场景：
worker a 目前正在有n个任务子在执行（n个任务在hire worker的时候都没有发生错误），
此时worker a 也是负载最小的一个，新来了一个任务b， 任务b会被分配给woker a 执行， 但是在分配的时候检测到worker a不正常了， 此时采取的策略是关闭 worker a。 但是worker a此时有n个任务被绑定执行， 那岂不是这n个任务全部失败了？

**Comment by henrylee2cn** [comment]
```go
Worker interface {
	Health() bool
	Close() error
}
```
Worker是有开发者自己实现。Health方法应该能够正确反馈Worker当前健康状态。假如该Worker已经不健康，那么，它正在执行的任务也不会成功的，因此不会造成不良影响。另外，调用Close方法时，涉及资源竞争的问题，应该由开发者自己避免。

**Comment by carl-leopard** [comment]
好的。 🙏 🙏 🙏
